apiVersion: authz.infoblox.com/v1
kind: Group
metadata:
  name: all-users
  namespace: contacts
  labels:
    authz-namespace: authz
criteria:
  type: user
---
apiVersion: authz.infoblox.com/v1
kind: Group
metadata:
  name: engineers
  namespace: contacts
  labels:
    authz-namespace: authz
criteria:
  type: user
  department: admin
---
apiVersion: authz.authz.infoblox.com/v1
kind: Group
metadata:
  name: all-resources
  namespace: contacts
  labels:
    authz-namespace: authz
criteria:
  type: none
---
apiVersion: authz.infoblox.com/v1
kind: RoleAssignment
metadata:
  name: contacts-all-users
  namespace: contacts
  labels:
    authz-namespace: authz
subjectgroups:
- all-users
roles:
- contacts-read-only
resourcegroups:
- all-resources
---
apiVersion: authz.infoblox.com/v1
kind: RoleAssignment
metadata:
  name: contacts-admin
  namespace: contacts
  labels:
    authz-namespace: authz
subjectgroups:
- engineers
roles:
- contacts-read-write
resourcegroups:
- all-resources
---
apiVersion: authz.infoblox.com/v1
kind: Role
metadata:
  name: contacts-read-only
  namespace: contacts
  labels:
    authz-namespace: authz
permissions:
  - contacts-read
---
apiVersion: authz.infoblox.com/v1
kind: Role
metadata:
  name: contacts-read-write
  namespace: contacts
  labels:
    authz-namespace: authz
permissions:
  - contacts-read
  - contacts-write
---
apiVersion: authz.infoblox.com/v1
kind: Permission
metadata:
  name: contacts-read
  namespace: contacts
  labels:
    authz-namespace: authz
operations:
  - Contacts.List
  - Contacts.Get
---
apiVersion: authz.infoblox.com/v1
kind: Permission
metadata:
  name: contacts-write
  namespace: contacts
  labels:
    authz-namespace: authz
operations:
  - Contacts.Create
  - Contacts.Update
  - Contacts.Delete
  - Contacts.SendSMS